spring:
  application:
    name: cloud-client-feign-demo
eureka:
  client:
    register-with-eureka: true
    service-url:
      difaultzone: http://localhost:8000/eureka/
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}
      