spring:
  application:
    name: cloud-client-feign-demo

server:
  port: 8222

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
      